# Settings for committed tool
# [Committed Configuration Reference](https://github.com/crate-ci/committed/blob/master/docs/reference.md)

subject_length = 50
subject_capitalized = false
subject_not_punctuated = true
imperative_subject = true
no_fixup = true
no_wip = false
hard_line_length = 0
line_length = 72
style = "none"
allowed_types = [
    "fix",
    "feat",
    "chore",
    "docs",
    "style",
    "refactor",
    "perf",
    "test",
]
merge_commit = true
