

# # declares name of CLI app and where the insertion point is
# [tool.poetry.scripts]
# cli-app-name = "pkg_name.commands:app"


[tool.isort]
# compatibility with Black formatter
profile = "black"


[tool.pylint]
disable = [
    # "C0303",  # trailing-whitespace -- interferes with docstring markdown
    "R0903",  # too-few-public-methods -- interferes with type capture of program logic
]

[tool.pylint.format]
# line length to match Black formatter
max-line-length = "88"


[tool.pyright]
include = ["src"]
exclude = [".venv",
    "src/experimental",
    "src/typestubs",
  "**/__pycache__"
]
# utilizing the fact that we've set Poetry `virtualenv.in-project` to true
venvPath = "."
venv = ".venv"

typeCheckingMode = "basic"  # "off", "basic", "strict"
reportMissingImports = true
reportMissingTypeStubs = true

executionEnvironments = [
  { root = "src" }
]


[tool.pytest.ini_options]
# adds the following paths to pythonpath, specified relative to root dir
addopts = "--doctest-modules"
pythonpath = [
    "src",
]
